name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
  test-2022:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2022/haskell
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: ./2022/haskell/.stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2.5'
          enable-stack: true
          stack-version: '2.9.1'
      - name: Build
        run: stack build
      - name: Run doctest
        run: stack exec -- doctest src/
